name: Build

on:
  push:
    branches:
      - master
      - 'ver/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Set Base Url
        run: |
          BRANCH=$(echo ${GITHUB_REF} | sed -e 's/refs\/heads\///')
          BEFORE='base: '''
          if [[ $BRANCH == ver/* ]]; then
            BRANCH_NAME=$(echo $BRANCH | sed 's|origin/||')
            AFTER=$(echo $BRANCH_NAME | sed 's|build/ver/||')
            AFTER="base: '/${AFTER}/'"
          else
            AFTER='base: '''
          fi
          echo $AFTER
          sed -i "s/${BEFORE}/${AFTER}/g" "./docs/.vitepress/config.mts"

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: yarn install

      - name: Build Docs
        run: 'yarn run docs:build'

      - name: Push to Build Branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          BRANCH=$(echo ${GITHUB_REF} | sed -e 's/refs\/heads\///')
          TARGET_BRANCH="build/${BRANCH}"
          
          if git ls-remote --heads origin ${TARGET_BRANCH} | grep ${TARGET_BRANCH}; then
            git push origin --delete ${TARGET_BRANCH}
          fi
          
          find . -mindepth 1 -maxdepth 1 ! -name 'docs' ! -name '.git' -exec rm -rf {} +
          find docs -mindepth 1 -maxdepth 1 ! -name '.vitepress' -exec rm -rf {} +
          cp -r docs/.vitepress/dist/* .
          rm -rf docs

          git checkout -b "${TARGET_BRANCH}"
          git add .
          git commit -m "GitHub Actions Auto Build ${BRANCH}"
          
          echo "Branch: ${BRANCH}"
          echo "Pushing to ${TARGET_BRANCH}"
          
          git push origin "${TARGET_BRANCH}"